import type { FeedGroup } from '~/types/feed'
import type { FeedGroup } from '~/types/feed'
import { getFavicon, getGhAvatar, getGhIcon, getQqAvatar, QqAvatarSize } from './utils/img'

export default [
			{
		name: '网上邻居',
		desc: '哔——啵——电波通讯中，欢迎常来串门。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '张洪Heo',
				desc: '分享设计与科技生活',
				link: 'https://blog.zhheo.com/',
				feed: 'https://blog.zhheo.com/atom.xml',
				icon: 'https://blog.zhheo.com/img/favicon4.0.webp',
				avatar: 'https://bu.dusays.com/2022/12/28/63ac2812183aa.png',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-02-02',
				comment: '知名博主，其博客设计风格被众多人借鉴。',
			},
			{
				author: 'Revincx',
				sitenick: '小破站',
				title: 'Revincx的小破站',
				link: 'https://blog.revincx.icu/',
				feed: 'https://blog.revincx.icu/atom.xml',
				icon: 'https://blog.revincx.icu/images/favico.png',
				avatar: 'https://weavatar.com/avatar/20eed6a268787c9a751165bc1ec56e90',
				archs: ['Hexo', 'Vercel'],
				date: '2024-01-20',
				comment: '编程、互联网上的信息的分享与记录。',
			},
			{
				author: '荷戟独彷徨',
				title: 'Sov2ex',
				desc: '一个更易读的 V2EX 第三方前端',
				link: 'https://sov2ex.vercel.app',
				feed: 'https://sov2ex.vercel.app/atom.xml',
				icon: 'https://sov2ex.vercel.app/favicon.ico',
				archs: ['SvelteKit', 'Vercel', 'Worker'],
				date: '2024-11-16',
			},
			{
				author: 'W4J1e',
				title: 'W4J1e',
				link: 'https://w4j1e.top',
				feed: 'https://w4j1e.top/atom.xml',
				icon: 'https://w4j1e.top/assets/icon-ixFTltwP.png',
				avatar: 'https://s2.loli.net/2022/06/05/3hx4XgZrWFJTPqY.jpg',
				archs: ['Astro', 'Vite', 'Vercel'],
				date: '2024-03-14',
			},
			{
				author: 'hrww555',
				title: 'HRWW',
				link: 'https://www.hrww.news/',
				feed: 'https://www.hrww.news/atom.xml',
				icon: 'https://www.hrww.news/favicon.ico',
				archs: ['Hexo', 'Vercel'],
				date: '2024-01-03',
				comment:
					'一个纯静态、正经写了 CI/CD 的 Hexo 博客。',
			},
			{
				author: 'abloom',
				sitenick: 'EEEs',
				title: 'EEEs Blog',
				link: 'https://eees.blog/',
				feed: 'https://eees.blog/atom.xml',
				icon: getGhIcon('abloom25'),
				avatar: getGhAvatar('abloom25'),
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '初中生，技术学习中。',
			},
			{
				author: '晓空',
				sitenick: '空域',
				title: '晓空blog',
				desc: '探索更大的世界',
				link: 'https://blog.moeworld.tech/',
				feed: 'https://blog.moeworld.tech/feed/',
				icon: 'https://blog.moeworld.tech/wp-content/uploads/2024/08/cropped-favicon-32x32.png',
				avatar: 'https://blog.moeworld.tech/wp-content/themes/kratos-pjax-master/static/images/photo.jpg',
				archs: ['WordPress', 'Cloudflare'],
				date: '2024-02-25',
				comment: '技术折腾笔记。',
			},
			{
				author: 'Kegongteng',
				desc: 'Blogger / Technophile / Thinker',
				link: 'https://kevct.com/',
				feed: 'https://kevct.com/atom.xml',
				icon: 'https://www.google.com/s2/favicons?sz=64&domain=kevct.com',
				avatar: 'https://weavatar.com/avatar/9ea8dcafc14f3dd5c3d841eb1d9a811c',
				archs: ['Hexo', 'Cloudflare'],
				date: '2024-12-20',
				comment: '记录生活、兴趣与思考。',
			},
			{
				author: 'Ean',
				title: '蜗牛老湿',
				link: 'https://www.clouna.com/',
				feed: 'https://www.clouna.com/feed/',
				icon: 'https://www.clouna.com/favicon.ico',
				avatar: 'https://www.clouna.com/wp-content/uploads/2023/12/2db7c-zhanweitu-2.jpeg',
				archs: ['WordPress', 'UCloud UStatic'],
				date: '2024-02-02',
			},
			{
				author: '沈唁',
				sitenick: '博客',
				title: '沈唁志',
				link: 'https://qq52o.me/',
				feed: 'https://qq52o.me/atom.xml',
				icon: 'https://q.qlogo.cn/g?b=qq&nk=25297169&s=100',
				avatar: 'https://q.qlogo.cn/g?b=qq&nk=25297169&s=100',
				archs: ['Typecho', '服务器'],
				date: '2024-04-12',
			},
			{
				author: '♂Wing',
				title: 'Muma',
				link: 'https://muma0.vercel.app',
				feed: '',
				icon: '',
				avatar: '',
				archs: ['Astro', 'Vercel'],
				date: '2024-08-19',
				comment: '小透明的个人站',
			},
			{
				author: 'Chiayu',
				title: '卅弋江',
				desc: '都城遇冷，下江开始暖和了',
				link: 'https://chiayu.me/',
				feed: 'https://chiayu.me/atom.xml',
				icon: 'https://www.google.com/s2/favicons?domain=chiayu.me&sz=64',
				avatar: 'https://avatars.githubusercontent.com/u/67058039',
				archs: ['Astro', 'GitHub Pages'],
				date: '2024-02-02',
			},
			{
				author: 'LITT',
				title: 'LITT',
				link: 'https://blog.litt.cc/',
				feed: 'https://blog.litt.cc/feed',
				icon: 'https://www.google.com/s2/favicons?domain=blog.litt.cc&sz=64',
				avatar: 'https://gravatar.litt.cc/avatar/litt?size=256',
				archs: ['WordPress', 'Cloudflare'],
				date: '2025-01-18',
				comment: '学有所成，受益匪浅。',
			},
			{
				author: 'Harry',
				title: 'Harry的自留地',
				link: 'https://www.licoy.cn',
				feed: 'https://www.licoy.cn/atom.xml',
				icon: 'https://www.licoy.cn/wp-content/uploads/2023/09/cropped-licoy_logo_1024.png',
				avatar: 'https://www.licoy.cn/wp-content/uploads/2023/09/cropped-licoy_logo_1024.png',
				archs: ['WordPress', 'LiteSpeed', 'Cloudflare'],
				date: '2025-01-18',
				comment: '半个博客圈老大哥。',
			},
			{
				author: 'HSU',
				sitenick: 'neverland',
				desc: 'Editor. Currently at SSPAI.',
				link: 'https://hsu.cy/',
				feed: 'https://hsu.cy/feed.xml',
				icon: getFavicon('hsu.cy'),
				avatar: 'https://cdnfile.sspai.com/2024/01/19/2e1141e8de2022...00x200r/gravity/center/crop/200x200/format/webp/ignore-error/1',
				archs: ['Hugo', 'Cloudflare'],
				date: '2025-09-03',
				comment: '长期记录多领域内容，涵盖数码产品软件配置、文艺作品品论等，兼具技术实践与观点分享。',
			},
		],
	},
] satisfies FeedGroup[]
